version: '3.6'

services:
  apache:
    image: ecidade_php56
    container_name: ecidade_php56
    build: ./php/5.6
    volumes:
     - ./:/var/www/html
    ports:
     - "80:80"
    networks:
     - ecidade

  postgresql:
    image: ecidade_postgresql95
    container_name: ecidade_postgresql95
    build: ./postgresql/9.5
    volumes:
     - ./:/var/www
    ports:
     - "5432:5432"
    networks:
     - ecidade

networks:
  ecidade:
    external:
      name: ecidade
