version: '2'

services:
  postgresql:
    container_name: postgresql
    build: ./postgresql
    volumes:
     - ./:/var/www
    links:
     - apache
    ports:
     - "5432:5432"
  apache:
    build: ./apache
    container_name: apache
    volumes:
     - ./:/var/www
    depends_on:
     - postgresql
    ports:
     - "80:80"