version: '3.6'

services:
  apache:
    image: ecidade_php56
    container_name: ecidade_php56
    build: ./php/5.6
    volumes:
     - ./:/var/www/html
    ports:
     - "8080:80"
    networks:
     - ecidade

  postgresql:
    image: ecidade_postgresql92
    container_name: ecidade_postgresql92
    build: ./postgresql/9.2
    volumes:
     - ./:/var/www
    ports:
     - "5433:5432" 
    networks:
     - ecidade

networks:
  ecidade:
    external:
      name: ecidade
