version: '3.6'

services:
  apache:
    image: ecidade_php53
    container_name: ecidade_php53
    build: ./php/5.3
    volumes:
     - ./:/var/www
    ports:
     - "8080:80"
    networks:
     - ecidade 

networks:
  ecidade:
    external:
      name: ecidade
